# Generated by Django 2.1 on 2022-07-17 04:26

from django.db import migrations, models

# Migrations apply changes performed on models to database schema
# When creating a new model or modify an existing one, create (1) and run (2) a new migration
# (1) "python manage.py makemigrations"
# (2) "python manage.py migrate"
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [  # Every migration can contain multiple operations
        migrations.CreateModel(
            name='Product',  # New database table called "Product" with the below fields/attributes
            fields=[
                # Django auto-created "id" b/c every database table MUST have an ID field
                # Used to uniquely identify records in databases
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]



